version: "3.8"
services:
  mysql:
    image: mysql:8.0
    container_name: genesis-ranking-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: genesis_ranking
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data:
